name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: enalmada/.github/.github/workflows/release.yml@main
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
